/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace LikeRegistry {
  export type LikeStruct = {
    fromHash: BytesLike;
    toHash: BytesLike;
    proofHash: BytesLike;
    timestamp: BigNumberish;
  };

  export type LikeStructOutput = [
    fromHash: string,
    toHash: string,
    proofHash: string,
    timestamp: bigint
  ] & {
    fromHash: string;
    toHash: string;
    proofHash: string;
    timestamp: bigint;
  };
}

export interface LikeRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allLikes"
      | "getLike"
      | "getLikesCount"
      | "hasLiked"
      | "isMatch"
      | "likeFee"
      | "likes"
      | "setLikeFee"
      | "submitLike"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "LikeSubmitted" | "MatchCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "allLikes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLike",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLikesCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasLiked",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isMatch",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "likeFee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "likes",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setLikeFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitLike",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "allLikes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getLike", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getLikesCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasLiked", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isMatch", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "likeFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "likes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setLikeFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "submitLike", data: BytesLike): Result;
}

export namespace LikeSubmittedEvent {
  export type InputTuple = [
    fromHash: BytesLike,
    toHash: BytesLike,
    proofHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    fromHash: string,
    toHash: string,
    proofHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    fromHash: string;
    toHash: string;
    proofHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatchCreatedEvent {
  export type InputTuple = [
    user1: BytesLike,
    user2: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [user1: string, user2: string, timestamp: bigint];
  export interface OutputObject {
    user1: string;
    user2: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LikeRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): LikeRegistry;
  waitForDeployment(): Promise<this>;

  interface: LikeRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allLikes: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint] & {
        fromHash: string;
        toHash: string;
        proofHash: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getLike: TypedContractMethod<
    [index: BigNumberish],
    [LikeRegistry.LikeStructOutput],
    "view"
  >;

  getLikesCount: TypedContractMethod<[], [bigint], "view">;

  hasLiked: TypedContractMethod<
    [from: BytesLike, to: BytesLike],
    [boolean],
    "view"
  >;

  isMatch: TypedContractMethod<
    [user1: BytesLike, user2: BytesLike],
    [boolean],
    "view"
  >;

  likeFee: TypedContractMethod<[], [bigint], "view">;

  likes: TypedContractMethod<
    [arg0: BytesLike, arg1: BytesLike],
    [boolean],
    "view"
  >;

  setLikeFee: TypedContractMethod<[_fee: BigNumberish], [void], "nonpayable">;

  submitLike: TypedContractMethod<
    [fromHash: BytesLike, toHash: BytesLike, proofHash: BytesLike],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allLikes"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint] & {
        fromHash: string;
        toHash: string;
        proofHash: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLike"
  ): TypedContractMethod<
    [index: BigNumberish],
    [LikeRegistry.LikeStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLikesCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasLiked"
  ): TypedContractMethod<[from: BytesLike, to: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isMatch"
  ): TypedContractMethod<
    [user1: BytesLike, user2: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "likeFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "likes"
  ): TypedContractMethod<[arg0: BytesLike, arg1: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "setLikeFee"
  ): TypedContractMethod<[_fee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitLike"
  ): TypedContractMethod<
    [fromHash: BytesLike, toHash: BytesLike, proofHash: BytesLike],
    [void],
    "payable"
  >;

  getEvent(
    key: "LikeSubmitted"
  ): TypedContractEvent<
    LikeSubmittedEvent.InputTuple,
    LikeSubmittedEvent.OutputTuple,
    LikeSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "MatchCreated"
  ): TypedContractEvent<
    MatchCreatedEvent.InputTuple,
    MatchCreatedEvent.OutputTuple,
    MatchCreatedEvent.OutputObject
  >;

  filters: {
    "LikeSubmitted(bytes32,bytes32,bytes32,uint256)": TypedContractEvent<
      LikeSubmittedEvent.InputTuple,
      LikeSubmittedEvent.OutputTuple,
      LikeSubmittedEvent.OutputObject
    >;
    LikeSubmitted: TypedContractEvent<
      LikeSubmittedEvent.InputTuple,
      LikeSubmittedEvent.OutputTuple,
      LikeSubmittedEvent.OutputObject
    >;

    "MatchCreated(bytes32,bytes32,uint256)": TypedContractEvent<
      MatchCreatedEvent.InputTuple,
      MatchCreatedEvent.OutputTuple,
      MatchCreatedEvent.OutputObject
    >;
    MatchCreated: TypedContractEvent<
      MatchCreatedEvent.InputTuple,
      MatchCreatedEvent.OutputTuple,
      MatchCreatedEvent.OutputObject
    >;
  };
}
