/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace MatchRegistry {
  export type MatchStruct = {
    user1: BytesLike;
    user2: BytesLike;
    timestamp: BigNumberish;
    active: boolean;
  };

  export type MatchStructOutput = [
    user1: string,
    user2: string,
    timestamp: bigint,
    active: boolean
  ] & { user1: string; user2: string; timestamp: bigint; active: boolean };
}

export interface MatchRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "deactivateMatch"
      | "getMatch"
      | "getMatchesCount"
      | "getUserMatches"
      | "isMatched"
      | "matches"
      | "registerMatch"
      | "userMatches"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "MatchDeactivated" | "MatchRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "deactivateMatch",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMatch",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMatchesCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserMatches",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isMatched",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "matches",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerMatch",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userMatches",
    values: [BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "deactivateMatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMatch", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMatchesCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserMatches",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isMatched", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "matches", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerMatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userMatches",
    data: BytesLike
  ): Result;
}

export namespace MatchDeactivatedEvent {
  export type InputTuple = [matchId: BigNumberish];
  export type OutputTuple = [matchId: bigint];
  export interface OutputObject {
    matchId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatchRegisteredEvent {
  export type InputTuple = [
    matchId: BigNumberish,
    user1: BytesLike,
    user2: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    matchId: bigint,
    user1: string,
    user2: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    matchId: bigint;
    user1: string;
    user2: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MatchRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): MatchRegistry;
  waitForDeployment(): Promise<this>;

  interface: MatchRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deactivateMatch: TypedContractMethod<
    [matchId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getMatch: TypedContractMethod<
    [matchId: BigNumberish],
    [MatchRegistry.MatchStructOutput],
    "view"
  >;

  getMatchesCount: TypedContractMethod<[], [bigint], "view">;

  getUserMatches: TypedContractMethod<
    [userHash: BytesLike],
    [string[]],
    "view"
  >;

  isMatched: TypedContractMethod<
    [arg0: BytesLike, arg1: BytesLike],
    [boolean],
    "view"
  >;

  matches: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, boolean] & {
        user1: string;
        user2: string;
        timestamp: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  registerMatch: TypedContractMethod<
    [user1: BytesLike, user2: BytesLike],
    [void],
    "nonpayable"
  >;

  userMatches: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deactivateMatch"
  ): TypedContractMethod<[matchId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getMatch"
  ): TypedContractMethod<
    [matchId: BigNumberish],
    [MatchRegistry.MatchStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMatchesCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserMatches"
  ): TypedContractMethod<[userHash: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "isMatched"
  ): TypedContractMethod<[arg0: BytesLike, arg1: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "matches"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, boolean] & {
        user1: string;
        user2: string;
        timestamp: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerMatch"
  ): TypedContractMethod<
    [user1: BytesLike, user2: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userMatches"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  getEvent(
    key: "MatchDeactivated"
  ): TypedContractEvent<
    MatchDeactivatedEvent.InputTuple,
    MatchDeactivatedEvent.OutputTuple,
    MatchDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "MatchRegistered"
  ): TypedContractEvent<
    MatchRegisteredEvent.InputTuple,
    MatchRegisteredEvent.OutputTuple,
    MatchRegisteredEvent.OutputObject
  >;

  filters: {
    "MatchDeactivated(uint256)": TypedContractEvent<
      MatchDeactivatedEvent.InputTuple,
      MatchDeactivatedEvent.OutputTuple,
      MatchDeactivatedEvent.OutputObject
    >;
    MatchDeactivated: TypedContractEvent<
      MatchDeactivatedEvent.InputTuple,
      MatchDeactivatedEvent.OutputTuple,
      MatchDeactivatedEvent.OutputObject
    >;

    "MatchRegistered(uint256,bytes32,bytes32,uint256)": TypedContractEvent<
      MatchRegisteredEvent.InputTuple,
      MatchRegisteredEvent.OutputTuple,
      MatchRegisteredEvent.OutputObject
    >;
    MatchRegistered: TypedContractEvent<
      MatchRegisteredEvent.InputTuple,
      MatchRegisteredEvent.OutputTuple,
      MatchRegisteredEvent.OutputObject
    >;
  };
}
