/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface PaymentManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getMessageCredits"
      | "isPremium"
      | "messageCredits"
      | "messageFee"
      | "payForMessages"
      | "payForSwipe"
      | "premiumUnlockFee"
      | "premiumUsers"
      | "setFees"
      | "storeMessageProof"
      | "swipeFee"
      | "unlockPremium"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MessagePayment"
      | "MessageProofStored"
      | "PremiumUnlocked"
      | "SwipePayment"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getMessageCredits",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isPremium",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "messageCredits",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "messageFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "payForMessages",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "payForSwipe",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "premiumUnlockFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "premiumUsers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFees",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "storeMessageProof",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "swipeFee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "unlockPremium",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "getMessageCredits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isPremium", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "messageCredits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "messageFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "payForMessages",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "payForSwipe",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "premiumUnlockFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "premiumUsers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setFees", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "storeMessageProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "swipeFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "unlockPremium",
    data: BytesLike
  ): Result;
}

export namespace MessagePaymentEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    credits: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    amount: bigint,
    credits: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    amount: bigint;
    credits: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MessageProofStoredEvent {
  export type InputTuple = [
    matchHash: BytesLike,
    messageHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    matchHash: string,
    messageHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    matchHash: string;
    messageHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PremiumUnlockedEvent {
  export type InputTuple = [user: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [user: string, timestamp: bigint];
  export interface OutputObject {
    user: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwipePaymentEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [user: string, amount: bigint, timestamp: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PaymentManager extends BaseContract {
  connect(runner?: ContractRunner | null): PaymentManager;
  waitForDeployment(): Promise<this>;

  interface: PaymentManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getMessageCredits: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  isPremium: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  messageCredits: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  messageFee: TypedContractMethod<[], [bigint], "view">;

  payForMessages: TypedContractMethod<[count: BigNumberish], [void], "payable">;

  payForSwipe: TypedContractMethod<[], [void], "payable">;

  premiumUnlockFee: TypedContractMethod<[], [bigint], "view">;

  premiumUsers: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  setFees: TypedContractMethod<
    [_swipe: BigNumberish, _message: BigNumberish, _premium: BigNumberish],
    [void],
    "nonpayable"
  >;

  storeMessageProof: TypedContractMethod<
    [matchHash: BytesLike, messageHash: BytesLike],
    [void],
    "nonpayable"
  >;

  swipeFee: TypedContractMethod<[], [bigint], "view">;

  unlockPremium: TypedContractMethod<[], [void], "payable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getMessageCredits"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "isPremium"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "messageCredits"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "messageFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "payForMessages"
  ): TypedContractMethod<[count: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "payForSwipe"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "premiumUnlockFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "premiumUsers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "setFees"
  ): TypedContractMethod<
    [_swipe: BigNumberish, _message: BigNumberish, _premium: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "storeMessageProof"
  ): TypedContractMethod<
    [matchHash: BytesLike, messageHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swipeFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "unlockPremium"
  ): TypedContractMethod<[], [void], "payable">;

  getEvent(
    key: "MessagePayment"
  ): TypedContractEvent<
    MessagePaymentEvent.InputTuple,
    MessagePaymentEvent.OutputTuple,
    MessagePaymentEvent.OutputObject
  >;
  getEvent(
    key: "MessageProofStored"
  ): TypedContractEvent<
    MessageProofStoredEvent.InputTuple,
    MessageProofStoredEvent.OutputTuple,
    MessageProofStoredEvent.OutputObject
  >;
  getEvent(
    key: "PremiumUnlocked"
  ): TypedContractEvent<
    PremiumUnlockedEvent.InputTuple,
    PremiumUnlockedEvent.OutputTuple,
    PremiumUnlockedEvent.OutputObject
  >;
  getEvent(
    key: "SwipePayment"
  ): TypedContractEvent<
    SwipePaymentEvent.InputTuple,
    SwipePaymentEvent.OutputTuple,
    SwipePaymentEvent.OutputObject
  >;

  filters: {
    "MessagePayment(address,uint256,uint256,uint256)": TypedContractEvent<
      MessagePaymentEvent.InputTuple,
      MessagePaymentEvent.OutputTuple,
      MessagePaymentEvent.OutputObject
    >;
    MessagePayment: TypedContractEvent<
      MessagePaymentEvent.InputTuple,
      MessagePaymentEvent.OutputTuple,
      MessagePaymentEvent.OutputObject
    >;

    "MessageProofStored(bytes32,bytes32,uint256)": TypedContractEvent<
      MessageProofStoredEvent.InputTuple,
      MessageProofStoredEvent.OutputTuple,
      MessageProofStoredEvent.OutputObject
    >;
    MessageProofStored: TypedContractEvent<
      MessageProofStoredEvent.InputTuple,
      MessageProofStoredEvent.OutputTuple,
      MessageProofStoredEvent.OutputObject
    >;

    "PremiumUnlocked(address,uint256)": TypedContractEvent<
      PremiumUnlockedEvent.InputTuple,
      PremiumUnlockedEvent.OutputTuple,
      PremiumUnlockedEvent.OutputObject
    >;
    PremiumUnlocked: TypedContractEvent<
      PremiumUnlockedEvent.InputTuple,
      PremiumUnlockedEvent.OutputTuple,
      PremiumUnlockedEvent.OutputObject
    >;

    "SwipePayment(address,uint256,uint256)": TypedContractEvent<
      SwipePaymentEvent.InputTuple,
      SwipePaymentEvent.OutputTuple,
      SwipePaymentEvent.OutputObject
    >;
    SwipePayment: TypedContractEvent<
      SwipePaymentEvent.InputTuple,
      SwipePaymentEvent.OutputTuple,
      SwipePaymentEvent.OutputObject
    >;
  };
}
